/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package finalprojectkel5;

import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;

public class MainMenu extends javax.swing.JFrame {
    private DefaultTableModel tableModel;
    private HashMap<String, Boolean> habitMap;
    public String username;
    /**
     * Creates new form loginMenu
     */
    public MainMenu() {
        this.username = UserDatabase.getCurrentUsername();
        initComponents();
        habitMap = new HashMap<>();
        initializeTable();
        initializeClock();
        if (username != null) {
            usernameLabel.setText("Welcome, " + username);
        } else {
            usernameLabel.setText("Welcome, Guest");
        }
    }
    
    private void initializeTable() {
    tableModel = (DefaultTableModel) habitTable.getModel();
    tableModel.setRowCount(0);
    }
    private void initializeClock() {
        // Set timer untuk memperbarui waktu setiap detik
        Timer timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                updateTime(); // Panggil metode untuk memperbarui waktu
            }
        });
        timer.start(); // Mulai timer

        updateTime(); // Set waktu awal saat aplikasi dimulai
    }
    
    
    private void updateTime() {
        String currentTime = new SimpleDateFormat("HH:mm:ss").format(new Date());
        String currentDate = new SimpleDateFormat("dd-MM-yyyy").format(new Date());
        timeLabel.setText(currentTime);
        dateLabel.setText(currentDate);
    }
    

    
    public boolean addHabit(String habitName) {
    boolean added = HabitData.addHabit(habitName); // Panggil metode dari HabitData
    if (added) {
        updateTable(); // Perbarui tabel jika habit berhasil ditambahkan
        }
        return added;
    }
    
    public boolean editHabit(String oldName, String newName) {
        if (habitMap.containsKey(newName)){
            return false;
        }
        Boolean status = habitMap.remove(oldName);
        habitMap.put(newName, status);
        updateTable();
        return true;
    }
    public void deleteHabit(String habitName) {
        HabitData.getHabits().remove(habitName); // Hapus dari HabitData
        updateTable(); // Perbarui tabel setelah menghapus habit
        }
    
    public void updateTable() {
    tableModel.setRowCount(0); // Kosongkan tabel
    for (Map.Entry<String, Boolean> entry : HabitData.getHabits().entrySet()) {
        Object[] row = { entry.getKey(), entry.getValue() };
        tableModel.addRow(row); // Tambahkan baris baru ke tabel
        }
    }
    
    public void toggleHabitStatus(int rowIndex) {
        String habitName = (String) tableModel.getValueAt(rowIndex, 0);
        boolean currentStatus = habitMap.get(habitName);
        habitMap.put(habitName, !currentStatus);
        updateTable();
    }
    
    public void resetHabits() {
        habitMap.clear();
        updateTable();
    }
    
    private void showSummary() {
        String timestamp = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date());
    
    // Ambil data kebiasaan dari HabitData
        HashMap<String, Boolean> habits = HabitData.getHabits();

    // Buat dan tampilkan SummaryFrame
        SummaryFrame summaryFrame = new SummaryFrame(habits, timestamp);
        summaryFrame.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        habitTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        timeLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        addHabitBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        editHabitBtn = new javax.swing.JButton();
        sumBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HabitMaker");

        jPanel1.setBackground(new java.awt.Color(255, 204, 51));

        jLabel1.setFont(new java.awt.Font("Square721 BT", 0, 48)); // NOI18N
        jLabel1.setText("HABITMAKER");

        habitTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Habit Name", "Completion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(habitTable);

        jLabel3.setText("Waktu :");

        jLabel4.setText("Tanggal :");

        timeLabel.setText("-");

        dateLabel.setText("-");

        usernameLabel.setText("Nama :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(timeLabel)
                                .addGap(57, 57, 57)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dateLabel)
                                .addGap(85, 85, 85)
                                .addComponent(usernameLabel)))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(timeLabel)
                    .addComponent(jLabel4)
                    .addComponent(dateLabel)
                    .addComponent(usernameLabel))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        addHabitBtn.setText("Add Habit");
        addHabitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addHabitBtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Square721 BT", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 204, 51));
        jLabel2.setText("Menu");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        editHabitBtn.setText("Edit Habit");
        editHabitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editHabitBtnActionPerformed(evt);
            }
        });

        sumBtn.setText("Summary");
        sumBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumBtnActionPerformed(evt);
            }
        });

        logoutBtn.setText("Log Out");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        resetBtn.setText("Reset");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(editHabitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addHabitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sumBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logoutBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(14, 14, 14))
                    .addComponent(resetBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addGap(40, 40, 40)
                .addComponent(addHabitBtn)
                .addGap(18, 18, 18)
                .addComponent(editHabitBtn)
                .addGap(18, 18, 18)
                .addComponent(sumBtn)
                .addGap(18, 18, 18)
                .addComponent(resetBtn)
                .addGap(18, 18, 18)
                .addComponent(logoutBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void setupTableListener(){
        habitTable.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt){
            int row = habitTable.rowAtPoint(evt.getPoint());
            int col = habitTable.columnAtPoint(evt.getPoint());
            
            if (col == 1){
            toggleHabitStatus(row);
                }
            }
        });
    }
    
    
    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        int input = JOptionPane.showConfirmDialog(null, "Apakah kamu yakin ingin logout?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (input == 0){
            LoginMenu lim = new LoginMenu();
            lim.setLocationRelativeTo(null);
            lim.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void addHabitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addHabitBtnActionPerformed
        // TODO add your handling code here:
        AddHabit ah = new AddHabit(this);
        ah.setLocationRelativeTo(null);
        ah.setVisible(true);
    }//GEN-LAST:event_addHabitBtnActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        // TODO add your handling code here:
        int input = JOptionPane.showConfirmDialog(null, "Apakah kamu yakin ingin reset?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (input == JOptionPane.YES_OPTION){
            HabitData.clearHabits();
            JOptionPane.showMessageDialog(this, "Semua habit sudah direset!");
            updateTable();
        }
    }//GEN-LAST:event_resetBtnActionPerformed

    
    private void editHabitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editHabitBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = habitTable.getSelectedRow();
        if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Pilih habit yang ingin diedit!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    String habitName = (String) habitTable.getValueAt(selectedRow, 0);
    EditHabit eh = new EditHabit(this, habitName); // Pastikan Anda mengirimkan habitName
    eh.setLocationRelativeTo(null);
    eh.setVisible(true);
    }//GEN-LAST:event_editHabitBtnActionPerformed

    private void sumBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumBtnActionPerformed
        // TODO add your handling code here:
        showSummary();
    }//GEN-LAST:event_sumBtnActionPerformed
  
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addHabitBtn;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JButton editHabitBtn;
    private javax.swing.JTable habitTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton resetBtn;
    private javax.swing.JButton sumBtn;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables


    
}
